**Agrupación y Segmentación de Vecindarios en la Ciudad de Toronto, Canadá**

**Parte 1:**

In [16]:
#Importamos librería pandas
import pandas as pd

In [17]:
url = "https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M"

In [18]:
W_Postal_Codes = pd.read_html(url)

In [19]:
df_OriginalTable = W_Postal_Codes[0]
df_OriginalTable.head()

,0,1,2,3,4,5,6,7,8
0,M1ANot assigned,M2ANot assigned,M3ANorth York(Parkwoods),M4ANorth York(Victoria Village),M5ADowntown Toronto(Regent Park / Harbourfront),M6ANorth York(Lawrence Manor / Lawrence Heights),M7AQueen's Park(Ontario Provincial Government),M8ANot assigned,M9AEtobicoke(Islington Avenue)
1,M1BScarborough(Malvern / Rouge),M2BNot assigned,M3BNorth York(Don Mills)North,M4BEast York(Parkview Hill / Woodbine Gardens),"M5BDowntown Toronto(Garden District, Ryerson)",M6BNorth York(Glencairn),M7BNot assigned,M8BNot assigned,M9BEtobicoke(West Deane Park / Princess Garden...
2,M1CScarborough(Rouge Hill / Port Union / Highl...,M2CNot assigned,M3CNorth York(Don Mills)South(Flemingdon Park),M4CEast York(Woodbine Heights),M5CDowntown Toronto(St. James Town),M6CYork(Humewood-Cedarvale),M7CNot assigned,M8CNot assigned,M9CEtobicoke(Eringate / Bloordale Gardens / Ol...
3,M1EScarborough(Guildwood / Morningside / West ...,M2ENot assigned,M3ENot assigned,M4EEast Toronto(The Beaches),M5EDowntown Toronto(Berczy Park),M6EYork(Caledonia-Fairbanks),M7ENot assigned,M8ENot assigned,M9ENot assigned
4,M1GScarborough(Woburn),M2GNot assigned,M3GNot assigned,M4GEast York(Leaside),M5GDowntown Toronto(Central Bay Street),M6GDowntown Toronto(Christie),M7GNot assigned,M8GNot assigned,M9GNot assigned

In [20]:
#Separamos Códigos Postales y descripción de Municipios y Vecindarios
Code = []
Desc = []
for index, row in df_OriginalTable.iterrows():  #recorrer filas
  for x in row:        #recorrrer cada celda 
    Code.append(x[:3]) #obtener lista con los Coódigos Postales
    Desc.append(x[3:]) #lista de descripción de Municipios y Vecindarios

In [21]:
#Observamos los primeros 5 Códigos Postales obtenidas en la lista
Code[0:5]

['M1A', 'M2A', 'M3A', 'M4A', 'M5A']

In [22]:
#Observamos las primeras 5 descripciones de Municipios y Vecindarios obtenidos en la lista
Desc[0:5]

['Not assigned',
 'Not assigned',
 'North York(Parkwoods)',
 'North York(Victoria Village)',
 'Downtown Toronto(Regent Park / Harbourfront)']

In [23]:
#Creamos un nuevo DataFrame con las 2 listas obtenidas
df_ReorganizedTable = pd.DataFrame()
df_ReorganizedTable['PostalCode'] = Code
df_ReorganizedTable['Description'] = Desc
df_ReorganizedTable.head()

  PostalCode                                   Description
0        M1A                                  Not assigned
1        M2A                                  Not assigned
2        M3A                         North York(Parkwoods)
3        M4A                  North York(Victoria Village)
4        M5A  Downtown Toronto(Regent Park / Harbourfront)

In [24]:
#Eliminamos todas las filas donde hay valores 'Not assigned' en la descripción
df_ReorganizedTableClean = df_ReorganizedTable.loc[(df_ReorganizedTable != 'Not assigned').all(axis=1), :]

In [25]:
#Luego de eliminar filas reindexamos
df_ReorganizedTableClean.reset_index(drop=True, inplace=True)
df_ReorganizedTableClean.head()

  PostalCode                                    Description
0        M3A                          North York(Parkwoods)
1        M4A                   North York(Victoria Village)
2        M5A   Downtown Toronto(Regent Park / Harbourfront)
3        M6A  North York(Lawrence Manor / Lawrence Heights)
4        M7A    Queen's Park(Ontario Provincial Government)

In [26]:
# Separamos Municipios de Vecindarios 
Bor_Neigh = df_ReorganizedTableClean.Description.str.split('(',expand=True)
# Reemplazamos los simbolos de '/' por el de ','
Bor_Neigh[1] = Bor_Neigh[1].str.replace('/',',')
# Reemplazamos los simbolos de ')' por el de '' 
Bor_Neigh[1] = Bor_Neigh[1].str.replace(')','')
Bor_Neigh.columns = ['Borough','Neighborhood','None']
Bor_Neigh.drop(['None'], axis=1,inplace=True)
Bor_Neigh.head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.

            Borough                       Neighborhood
0        North York                          Parkwoods
1        North York                   Victoria Village
2  Downtown Toronto         Regent Park , Harbourfront
3        North York  Lawrence Manor , Lawrence Heights
4      Queen's Park      Ontario Provincial Government

In [27]:
#Obtenemos tabla final con las 3 columnas 'PostalCode','Borough'y'Neighborhood' 
df_data1 = pd.DataFrame()
df_data1 ['PostalCode'] = df_ReorganizedTableClean ['PostalCode']
df_data1 [['Borough','Neighborhood']] = Bor_Neigh
df_data1.head()

  PostalCode           Borough                       Neighborhood
0        M3A        North York                          Parkwoods
1        M4A        North York                   Victoria Village
2        M5A  Downtown Toronto         Regent Park , Harbourfront
3        M6A        North York  Lawrence Manor , Lawrence Heights
4        M7A      Queen's Park      Ontario Provincial Government

In [28]:
#Obtenemos dimensioones de la tabla de datos
df_data1.shape

(103, 3)