**Agrupación y Segmentación de Vecindarios en la Ciudad de Toronto, Canadá**

**Parte 1:**

In [33]:
#Importamos librería pandas
import pandas as pd

In [34]:
url = "https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M"

In [35]:
W_Postal_Codes = pd.read_html(url)

In [36]:
df_OriginalTable = W_Postal_Codes[0]
df_OriginalTable.head()

,0,1,2,3,4,5,6,7,8
0,M1ANot assigned,M2ANot assigned,M3ANorth York(Parkwoods),M4ANorth York(Victoria Village),M5ADowntown Toronto(Regent Park / Harbourfront),M6ANorth York(Lawrence Manor / Lawrence Heights),M7AQueen's Park(Ontario Provincial Government),M8ANot assigned,M9AEtobicoke(Islington Avenue)
1,M1BScarborough(Malvern / Rouge),M2BNot assigned,M3BNorth York(Don Mills)North,M4BEast York(Parkview Hill / Woodbine Gardens),"M5BDowntown Toronto(Garden District, Ryerson)",M6BNorth York(Glencairn),M7BNot assigned,M8BNot assigned,M9BEtobicoke(West Deane Park / Princess Garden...
2,M1CScarborough(Rouge Hill / Port Union / Highl...,M2CNot assigned,M3CNorth York(Don Mills)South(Flemingdon Park),M4CEast York(Woodbine Heights),M5CDowntown Toronto(St. James Town),M6CYork(Humewood-Cedarvale),M7CNot assigned,M8CNot assigned,M9CEtobicoke(Eringate / Bloordale Gardens / Ol...
3,M1EScarborough(Guildwood / Morningside / West ...,M2ENot assigned,M3ENot assigned,M4EEast Toronto(The Beaches),M5EDowntown Toronto(Berczy Park),M6EYork(Caledonia-Fairbanks),M7ENot assigned,M8ENot assigned,M9ENot assigned
4,M1GScarborough(Woburn),M2GNot assigned,M3GNot assigned,M4GEast York(Leaside),M5GDowntown Toronto(Central Bay Street),M6GDowntown Toronto(Christie),M7GNot assigned,M8GNot assigned,M9GNot assigned

In [37]:
#Separamos Códigos Postales y descripción de Municipios y Vecindarios
Code = []
Desc = []
for index, row in df_OriginalTable.iterrows():  #recorrer filas
  for x in row:        #recorrrer cada celda 
    Code.append(x[:3]) #obtener lista con los Coódigos Postales
    Desc.append(x[3:]) #lista de descripción de Municipios y Vecindarios

In [38]:
#Observamos los primeros 5 Códigos Postales obtenidas en la lista
Code[0:5]

['M1A', 'M2A', 'M3A', 'M4A', 'M5A']

In [39]:
#Observamos las primeras 5 descripciones de Municipios y Vecindarios obtenidos en la lista
Desc[0:5]

['Not assigned',
 'Not assigned',
 'North York(Parkwoods)',
 'North York(Victoria Village)',
 'Downtown Toronto(Regent Park / Harbourfront)']

In [40]:
#Creamos un nuevo DataFrame con las 2 listas obtenidas
df_ReorganizedTable = pd.DataFrame()
df_ReorganizedTable['PostalCode'] = Code
df_ReorganizedTable['Description'] = Desc
df_ReorganizedTable.head()

  PostalCode                                   Description
0        M1A                                  Not assigned
1        M2A                                  Not assigned
2        M3A                         North York(Parkwoods)
3        M4A                  North York(Victoria Village)
4        M5A  Downtown Toronto(Regent Park / Harbourfront)

In [41]:
#Eliminamos todas las filas donde hay valores 'Not assigned' en la descripción
df_ReorganizedTableClean = df_ReorganizedTable.loc[(df_ReorganizedTable != 'Not assigned').all(axis=1), :]

In [42]:
#Luego de eliminar filas reindexamos
df_ReorganizedTableClean.reset_index(drop=True, inplace=True)
df_ReorganizedTableClean.head()

  PostalCode                                    Description
0        M3A                          North York(Parkwoods)
1        M4A                   North York(Victoria Village)
2        M5A   Downtown Toronto(Regent Park / Harbourfront)
3        M6A  North York(Lawrence Manor / Lawrence Heights)
4        M7A    Queen's Park(Ontario Provincial Government)

In [43]:
# Separamos Municipios de Vecindarios 
Bor_Neigh = df_ReorganizedTableClean.Description.str.split('(',expand=True)
# Reemplazamos los simbolos de '/' por el de ','
Bor_Neigh[1] = Bor_Neigh[1].str.replace('/',',')
# Reemplazamos los simbolos de ')' por el de '' 
Bor_Neigh[1] = Bor_Neigh[1].str.replace(')','')
Bor_Neigh.columns = ['Borough','Neighborhood','None']
Bor_Neigh.drop(['None'], axis=1,inplace=True)
Bor_Neigh.head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.

            Borough                       Neighborhood
0        North York                          Parkwoods
1        North York                   Victoria Village
2  Downtown Toronto         Regent Park , Harbourfront
3        North York  Lawrence Manor , Lawrence Heights
4      Queen's Park      Ontario Provincial Government

In [44]:
#Obtenemos tabla final con las 3 columnas 'PostalCode','Borough'y'Neighborhood' 
df_data1 = pd.DataFrame()
df_data1 ['PostalCode'] = df_ReorganizedTableClean ['PostalCode']
df_data1 [['Borough','Neighborhood']] = Bor_Neigh
df_data1.head()

  PostalCode           Borough                       Neighborhood
0        M3A        North York                          Parkwoods
1        M4A        North York                   Victoria Village
2        M5A  Downtown Toronto         Regent Park , Harbourfront
3        M6A        North York  Lawrence Manor , Lawrence Heights
4        M7A      Queen's Park      Ontario Provincial Government

In [46]:
#Obtenemos dimensioones de la tabla de datos
df_data1.shape

(103, 3)

**Parte 2:**

In [49]:
#descargamos archivo csv con los datos geoespaciales
!wget -O Geospatial_data.csv http://cocl.us/Geospatial_data

URL transformed to HTTPS due to an HSTS policy
--2022-08-08 15:31:48--  https://cocl.us/Geospatial_data
Resolving cocl.us (cocl.us)... 23.221.22.114, 23.221.22.117, 2600:1404:6400:34::172f:33b9, ...
Connecting to cocl.us (cocl.us)|23.221.22.114|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://ibm.box.com/shared/static/9afzr83pps4pwf2smjjcf1y5mvgb18rr.csv [following]
--2022-08-08 15:31:49--  https://ibm.box.com/shared/static/9afzr83pps4pwf2smjjcf1y5mvgb18rr.csv
Resolving ibm.box.com (ibm.box.com)... 107.152.29.197
Connecting to ibm.box.com (ibm.box.com)|107.152.29.197|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /public/static/9afzr83pps4pwf2smjjcf1y5mvgb18rr.csv [following]
--2022-08-08 15:31:49--  https://ibm.box.com/public/static/9afzr83pps4pwf2smjjcf1y5mvgb18rr.csv
Reusing existing connection to ibm.box.com:443.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://ibm.ent.box.com/public/static/9afzr83pps4pwf2smjjcf1y5mvgb18rr.csv [following]
--2022-08-08 15:31:49--  https://ibm.ent.box.com/public/static/9afzr83pps4pwf2smjjcf1y5mvgb18rr.csv
Resolving ibm.ent.box.com (ibm.ent.box.com)... 74.112.186.144
Connecting to ibm.ent.box.com (ibm.ent.box.com)|74.112.186.144|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://dl2.boxcloud.com/d/1/b1!b-TKjpKur2Gvq5G7eOFdhSg5V_VLtdajaTViBRMcTAwxI0kmDafdzeYcVs8K5_rgXjgPYIExMNAqa47vU_qRHxCtSuR-vtax9s6szYO4A3amZM3lPD_4f9yord1qB3B_jE5aKU4LCwFHXJT6BqPHITBiBSBh46tQO68Z5FI0hdUOh4Fkp4YFquXlRfuKMBFZWLgDCUXHLZBNiAJjSPzNV4i8fpPEciySDzG6Zel3r617oh7-n6L9sy-DHB6TMH6nh2gSCqvseYyqv-X2etNlsyWEh253ar0hHQB8WlCuyJu4h76jKoABi_MDE98yGsLjP2ZI_kX1NIwAgExPfvHFkEW4XS1jkAuVNrlXkPToDhc16a_8gnyIpQXegBa2o-4vZ5My4YAJR2Upw7Ct6BYUjasykD8mqedWmZde3z5Scrl3ghYUVL9ug9pSjBHMhYEpfEmg073dSivCPl5ip5aPIIlMYsZd_foykUeUv3wV-bil4Sf9cqYNdXtoq_P-Vs6V1mSxilb3h4AOcRs_FuATmXoAtn39LcNPyhtFnWRhtzC198P5NjpMdUMdbfB4cs4c8j8dRmzcPjPNec9z0UwyLEPUpeBJC4kb3y952yKwv4Q0lg7O0Msjp8UEaPyCKyd8FgmgcoeCW8EKRPqXo_nUiu1JtogZD-zqORkmPgngiWC9OS90NPM7DgX9vlJap7ULPN8Np-Y0wz0OhCb-i_5Yd7zP9XZ-s-5OqLn3wLirSATn81dS0qEnpAfYaBmMozZmDhZfXLk8UvYAA09TJRCqNNTXRwa67vTbahrzsHWhG64ZcaZUFjbiflhfR7n23KNtABbgjDg9VyvpMQ0qABGe7DdbUpgokQ4Pc4RpKEJw7fNf1Kp7FB3mhV7WWjg8gIGoB-RzAp5cirw1BCno4wlQshp0JBPa3CXSqKJgS0rzkm4VGVP5IKR8owvAjo9pKq27qbKEduNCdAbP81sXSUgm-KlwDOB4Q6xsCqCAs14VY3RxMdiKB7-x-SW-S_KuieuLQwBJvmCt9tJQMlnWuN9o07XxluuUZQPmzPYL7Vh-OFXfc1zoL7Smm1dAgbll1UzaSImbfDss-dlioBJogUgNwzWF-25RybK8P960CNWl3sz06hICBfEMT3boe5Q48x0SN7ZOYKMGyp5nHqVvJIqmL4fiMsMxSXKsPCmBc0fSK8hW7qeg0sn2bFBurVHskzYrukYRl_5a--wu2FAUQrALMb9twMN-uSdJ01hJhADKhQpXoCkPx6LofVsdhHBiGXtYQB96lyMg6ocsbqbh7JbNScKRYSqSYw0JwVvaNbdUEBIL4LaqcOc24dJX2GTQ7GORbgR97cNfm7ViDh7JPLRHi2CT3KWAhnwDgcnpNeWgRmYUbdnWjt7jVgQR4jmqIaEM4nffy8eQI4tVdtxWalCYjudrSKCYwNP-0o2VYfGa37Q8Kplegs1jAZ7OB7tRRTdQAT_xuhpknYo./download [following]
--2022-08-08 15:31:50--  https://dl2.boxcloud.com/d/1/b1!b-TKjpKur2Gvq5G7eOFdhSg5V_VLtdajaTViBRMcTAwxI0kmDafdzeYcVs8K5_rgXjgPYIExMNAqa47vU_qRHxCtSuR-vtax9s6szYO4A3amZM3lPD_4f9yord1qB3B_jE5aKU4LCwFHXJT6BqPHITBiBSBh46tQO68Z5FI0hdUOh4Fkp4YFquXlRfuKMBFZWLgDCUXHLZBNiAJjSPzNV4i8fpPEciySDzG6Zel3r617oh7-n6L9sy-DHB6TMH6nh2gSCqvseYyqv-X2etNlsyWEh253ar0hHQB8WlCuyJu4h76jKoABi_MDE98yGsLjP2ZI_kX1NIwAgExPfvHFkEW4XS1jkAuVNrlXkPToDhc16a_8gnyIpQXegBa2o-4vZ5My4YAJR2Upw7Ct6BYUjasykD8mqedWmZde3z5Scrl3ghYUVL9ug9pSjBHMhYEpfEmg073dSivCPl5ip5aPIIlMYsZd_foykUeUv3wV-bil4Sf9cqYNdXtoq_P-Vs6V1mSxilb3h4AOcRs_FuATmXoAtn39LcNPyhtFnWRhtzC198P5NjpMdUMdbfB4cs4c8j8dRmzcPjPNec9z0UwyLEPUpeBJC4kb3y952yKwv4Q0lg7O0Msjp8UEaPyCKyd8FgmgcoeCW8EKRPqXo_nUiu1JtogZD-zqORkmPgngiWC9OS90NPM7DgX9vlJap7ULPN8Np-Y0wz0OhCb-i_5Yd7zP9XZ-s-5OqLn3wLirSATn81dS0qEnpAfYaBmMozZmDhZfXLk8UvYAA09TJRCqNNTXRwa67vTbahrzsHWhG64ZcaZUFjbiflhfR7n23KNtABbgjDg9VyvpMQ0qABGe7DdbUpgokQ4Pc4RpKEJw7fNf1Kp7FB3mhV7WWjg8gIGoB-RzAp5cirw1BCno4wlQshp0JBPa3CXSqKJgS0rzkm4VGVP5IKR8owvAjo9pKq27qbKEduNCdAbP81sXSUgm-KlwDOB4Q6xsCqCAs14VY3RxMdiKB7-x-SW-S_KuieuLQwBJvmCt9tJQMlnWuN9o07XxluuUZQPmzPYL7Vh-OFXfc1zoL7Smm1dAgbll1UzaSImbfDss-dlioBJogUgNwzWF-25RybK8P960CNWl3sz06hICBfEMT3boe5Q48x0SN7ZOYKMGyp5nHqVvJIqmL4fiMsMxSXKsPCmBc0fSK8hW7qeg0sn2bFBurVHskzYrukYRl_5a--wu2FAUQrALMb9twMN-uSdJ01hJhADKhQpXoCkPx6LofVsdhHBiGXtYQB96lyMg6ocsbqbh7JbNScKRYSqSYw0JwVvaNbdUEBIL4LaqcOc24dJX2GTQ7GORbgR97cNfm7ViDh7JPLRHi2CT3KWAhnwDgcnpNeWgRmYUbdnWjt7jVgQR4jmqIaEM4nffy8eQI4tVdtxWalCYjudrSKCYwNP-0o2VYfGa37Q8Kplegs1jAZ7OB7tRRTdQAT_xuhpknYo./download
Resolving dl2.boxcloud.com (dl2.boxcloud.com)... 74.112.186.128
Connecting to dl2.boxcloud.com (dl2.boxcloud.com)|74.112.186.128|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2891 (2.8K) [text/csv]
Saving to: ‘Geospatial_data.csv’

Geospatial_data.csv 100%[===================>]   2.82K  --.-KB/s    in 0.002s

2022-08-08 15:31:50 (1.76 MB/s) - ‘Geospatial_data.csv’ saved [2891/2891]

In [50]:
Geospatial_data = pd.read_csv('Geospatial_data.csv')

In [51]:
Geospatial_data = Geospatial_data.rename(columns={'Postal Code':'PostalCode'})

In [52]:
Geospatial_data.head()

  PostalCode   Latitude  Longitude
0        M1B  43.806686 -79.194353
1        M1C  43.784535 -79.160497
2        M1E  43.763573 -79.188711
3        M1G  43.770992 -79.216917
4        M1H  43.773136 -79.239476

In [53]:
#Obtenemos dimensioones de la tabla de datos
Geospatial_data.shape

(103, 3)

In [54]:
#Utilizamos columna en común de las dos tablas 'PostalCode' para poder unirlas
df_data2 = pd.merge(df_data1, Geospatial_data, on ='PostalCode')
df_data2.head()

,PostalCode,Borough,Neighborhood,Latitude,Longitude
0,M3A,North York,Parkwoods,43.753259,-79.329656
1,M4A,North York,Victoria Village,43.725882,-79.315572
2,M5A,Downtown Toronto,"Regent Park , Harbourfront",43.654260,-79.360636
3,M6A,North York,"Lawrence Manor , Lawrence Heights",43.718518,-79.464763
4,M7A,Queen's Park,Ontario Provincial Government,43.662301,-79.389494

In [55]:
df_data2.shape

(103, 5)